knp_paginator:
    page_range: 5               # nombre de liens “autour” de la page courante
    default_options:
        page_name: page         # nom du paramètre dans l’URL (?page=2)
        sort_field_name: sort   # pour le tri
        sort_direction_name: direction
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable:   '@KnpPaginator/Pagination/bootstrap_v5_sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'
