controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\UtilisateurController\LoginController::adminDashboard

participant_dashboard:
    path: /participant/dashboard
    controller: App\Controller\UtilisateurController\LoginController::participantDashboard


